{% set version = "0.3-7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rborist
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rborist_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rborist/Rborist_{{ version }}.tar.gz
  sha256: 011efef9e6f304f752bd5013627dc8482f0e9d4cf1ec49503e97d3718f542596

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  # Unskip win when "CXX14 not defined" issue has a fix
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
    - r-base
    - r-rcpp >=0.12.2
    - r-data.table >=1.9.8
    - r-digest
  run:
    - {{ native }}gcc-libs         # [win]
    - r-base
    - r-rcpp >=0.12.2
    - r-data.table >=1.9.8
    - r-digest

test:
  commands:
    - $R -e "library('Rborist')"           # [not win]
    - "\"%R%\" -e \"library('Rborist')\""  # [win]

about:
  home: http://www.suiji.org/arborist, https://github.com/suiji/Arborist
  license: MPL-2.0 OR GPL-3.0-or-later
  summary: Scalable implementation of classification and regression forests, as described by Breiman (2001), <DOI:10.1023/A:1010933404324>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: Rborist
# Title: Extensible, Parallelizable Implementation of the Random Forest Algorithm
# Version: 0.2-2
# Date: 2019-9-8
# Author: Mark Seligman
# Maintainer: Mark Seligman <mseligman@suiji.org>
# BugReports: https://github.com/suiji/Arborist/issues
# SystemRequirements: g++ (>= 4.8)
# Description: Scalable implementation of classification and regression forests, as described by Breiman (2001), <DOI:10.1023/A:1010933404324>.
# URL: http://www.suiji.org/arborist, https://github.com/suiji/Arborist
# License: MPL (>= 2) | GPL (>= 2) | file LICENSE
# LazyLoad: yes
# Depends: R(>= 3.3)
# Imports: Rcpp (>= 0.12.2), data.table (>= 1.9.8), digest
# Suggests: testthat, knitr, rmarkdown
# VignetteBuilder: knitr
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Packaged: 2019-09-09 03:16:51 UTC; seligman
# Repository: CRAN
# Date/Publication: 2019-09-09 08:50:02 UTC
