bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: eNqwe/icbW+wf/k0nj1DNO/LL/5L9C/Y2fMsYa0023JKfujJuY7yO6QTTvzzQhLgo3JpNiUgVFxV/by84rjflNsTZmnv5Og36A26T6cc9MxSvU5R1M6B9c9nntauL/jzD/CkKeinSRZK2Hgwf4dHnBtFZdnKt5Wldh0RdhAiGl5m/hhZE6wASXO0zqbHDH1hJwkanrNFiP75+INJCg7+ZGfidm6yoRHhONqKplJ0uo+kih0i8D2tq0s6ooWQsOobbICPz7eA9weIPcYoNUX/Hz1XgkfDohUH5QKciomqHAqOi4HTdsV2iPVyMa1+nYjhT1W+cFnRdiFR9cC36U+gQT4g6UKHfXIIaoUsFOjHGM75wv7XGTExtPKSEegEnQuLFSEv+Oxsq099UnOV+6NfB+S8ZyRCVayROXS1MV3jcGkboRTD7ibwoJpRu7EjmOyzfTv7XRYbALWFZkLjd3xIjf7vNfy4HjlsAelCUgn4HX0DTBCPHMnRVGHpt+CQ+0LGPjSXb0P4w+lS/Zj3mxKfYxSFspOqNHp523W7ImFJH7q1UXThbIqii/XpwJ2MF1NgX9N9YkTRrXBIrefgUasrpdffICwTWWBimAJIJt5YYE/MiGIi9uUJJyDp9zFIV0kz3vYstMIt3OumgXvcQfcrG/oqQ07kYWZchRZV395MtM8=
conda_forge_output_validation: true
